FIXED: Possible unknown class exceptions in XPCE when trapping errors.
Notably can cause HTTP servers to trap the XPCE debugger when invalid
http requests are sent to them:

  ERROR: [Thread pce] http_request: Unknown class